name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing remote SSH commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/frontend-app
            git pull origin main
            
            cat > .env << 'EOF'
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
            EOF
            
            npm install
            npm run build